### ISSUE TITLE
THead sorting issue

### ISSUE THREAD

**Issue by petsoukos** [SimonPao-zz/smpSortableTable#2]
Hi there,
Thanks for this code.
Howerver, when I click a THead elemnt to sort the column it sorts only the first 2 rows.

**Comment by SimonPao-zz** [comment]
I haven't run into this particular issue myself. Perhaps you could show me your implementation and I could try to see why you're having trouble.

**Comment by SimonPao-zz** [comment]
Hello Again,
Thanks for letting me know about this. I checked it out and was able to reproduce. One of my recent changes broke sorting functionality when rendering using table data. The most recent commit should work now.
